In [1]:
# Importando libs em pyton
import numpy as np
import pandas as pd
import random as rd
from random import randint
import matplotlib.pyplot as pit

In [2]:
# Número de itens - 10
n = 10
numero_itens = np.arange(1, n + 1)

# Gerando randomicamente os pesos
pesos = [2.5, 1.8, 0.7, 2.1, 1.5, 2.2, 0.9, 1.6, 0.5, 1.1]

# Gerando randomicamente os valores de cada item
valores = [2000, 1450, 3400, 1900, 1300, 1000, 600, 1300, 400, 900]

# Nomes dos itens
nomes = [
    "Smartphone Samsung Galaxy S21",
    "Notebook Dell Inspiron 15",
    "Fone de Ouvido Bluetooth JBL",
    "Smartwatch Samsung Galaxy Watch 3",
    "Tablet Apple iPad 10.2",
    "Câmera Digital Canon EOS Rebel T7",
    "Mouse Gamer Logitech G Pro",
    "Teclado Mecânico Redragon Kumara",
    "Caixa de Som Bluetooth JBL GO",
    "Smartband Xiaomi Mi Band 6",
]

# Definindo o peso máximo para a mochila
max_peso_mochila = 7

In [3]:
for i in range(numero_itens.shape[0]):
    print(
        "Item: {} - Nome: {} - Peso: {} - Valor: {}".format(
            numero_itens[i], nomes[i], pesos[i], valores[i]
        )
    )

Item: 1 - Nome: Smartphone Samsung Galaxy S21 - Peso: 2.5 - Valor: 2000
Item: 2 - Nome: Notebook Dell Inspiron 15 - Peso: 1.8 - Valor: 1450
Item: 3 - Nome: Fone de Ouvido Bluetooth JBL - Peso: 0.7 - Valor: 3400
Item: 4 - Nome: Smartwatch Samsung Galaxy Watch 3 - Peso: 2.1 - Valor: 1900
Item: 5 - Nome: Tablet Apple iPad 10.2 - Peso: 1.5 - Valor: 1300
Item: 6 - Nome: Câmera Digital Canon EOS Rebel T7 - Peso: 2.2 - Valor: 1000
Item: 7 - Nome: Mouse Gamer Logitech G Pro - Peso: 0.9 - Valor: 600
Item: 8 - Nome: Teclado Mecânico Redragon Kumara - Peso: 1.6 - Valor: 1300
Item: 9 - Nome: Caixa de Som Bluetooth JBL GO - Peso: 0.5 - Valor: 400
Item: 10 - Nome: Smartband Xiaomi Mi Band 6 - Peso: 1.1 - Valor: 900


In [4]:
# Número de soluções ou indivíduos por população
solucao_por_populacao = 8
tamanho_populacao = (solucao_por_populacao, numero_itens.shape[0])

print("Tamanho da população: {}".format(tamanho_populacao))
print("Número de indivíduos: {}".format(solucao_por_populacao))
print("Número de itens: {}".format(numero_itens.shape[0]))

Tamanho da população: (8, 10)
Número de indivíduos: 8
Número de itens: 10


In [5]:
# Definindo o número de geracöes
n_geracoes = 10

# Criando a populacao onde somente um item sera levado por individuo
populacao_inicial = np.eye(tamanho_populacao[0], tamanho_populacao[1], k=0)

# Convertendo os tipos dos genes para inteiro
populacao_inicial = populacao_inicial.astype(int)


print("Populacao Inicial: \n{}".format(populacao_inicial))

Populacao Inicial: 
[[1 0 0 0 0 0 0 0 0 0]
 [0 1 0 0 0 0 0 0 0 0]
 [0 0 1 0 0 0 0 0 0 0]
 [0 0 0 1 0 0 0 0 0 0]
 [0 0 0 0 1 0 0 0 0 0]
 [0 0 0 0 0 1 0 0 0 0]
 [0 0 0 0 0 0 1 0 0 0]
 [0 0 0 0 0 0 0 1 0 0]]


In [6]:
# Função para calcular o fitness de cada indivíduo
def cal_fitness(peso, valor, populacao, max_peso_mochila):
    fitness = np.zeros(populacao.shape[0])
    # Percorre cada indivíduo
    for i in range(populacao.shape[0]):
        # Multiplica os itens que o indivíduo está levando pelo valor e soma
        S1 = np.sum(populacao[i] * valor)
        # Multiplica os itens que o indivíduo está levando pelo peso e soma
        S2 = np.sum(populacao[i] * peso)
        # Verifica se o peso não passou da capacidade máxima da mochila
        if S2 <= max_peso_mochila:
            # Armazena o fitness do indivíduo
            fitness[i] = S1
        else:
            # Passou da capacidade máxima, logo valor é 0
            fitness[i] = 0
    return fitness.astype(float)

In [ ]:
# Função para selecionar os indivíduos da próxima geração
def selecao_roleta(fitness, numero_pais, populacao):

    # Soma todos os fitness
    max_fitness = np.sum(fitness)

    # Calcula a probabilidade de cada indivíduo
    probabilidade = fitness / max_fitness

    # Realiza a seleção dos indivíduos
    selecionados = populacao[np.random.choice(len(populacao), size=numero_pais, p=probabilidade)]
    return selecionados

In [ ]:
def crossover(pais, numero_filhos):
    filhos = np.zeros((numero_filhos, pais.shape[1]), dtype=int)
    for i in range(numero_filhos):
        # Seleciona dois pais aleatórios
        pai1 = pais[rd.randint(0, pais.shape[0] - 1)]
        pai2 = pais[rd.randint(0, pais.shape[0] - 1)]
        # Realiza o crossover entre os dois pais
        ponto_crossover = rd.randint(1, pais.shape[1] - 1)
        filhos[i][:ponto_crossover] = pai1[:ponto_crossover]
        filhos[i][ponto_crossover:] = pai2[ponto_crossover:]
    return filhos